name: Native WebGPU Tests

on:
  push:
    branches: [main, master, dev, develop]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Pyton
        uses: actions/setup-python@v5

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Dawn Dependencies
        run: |
          pushd lib/dawn
          python tools/fetch_dawn_dependencies.py
          popd

      - name: Build and run
        run: |
          cd test 
          cmake -B build -DCMAKE_CXX_FLAGS="-Wall" -DCMAKE_C_FLAGS="-Wall"
          cmake --build build -j 8 &&
          ./build/Example


