name: Native WebGPU Tests

on:
  push:
    branches: [main, master, dev, develop]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run
        run: |
          cd test 
          cmake -B build --compile-no-warning-as-error
          cmake --build build &&
          ./build/Example


