name: Emscripten WebGPU Tests

on:
  push:
    branches: [main, master, dev, develop]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Chrome
        run: brew install --cask google-chrome
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '4.0.23'
            
      - name: Build
        run: |
          cd test 
          ./em_build_and_run